# Generated by Django 5.2.8 on 2025-11-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('teams', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('yt', 'YouTube'), ('m3u8', 'M3U8'), ('embed', 'Embedded Link')], max_length=10)),
                ('src', models.CharField(help_text='YouTube video ID or stream URL', max_length=500)),
                ('flag_left', models.URLField(blank=True, max_length=500, null=True)),
                ('flag_right', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
