# Generated by Django 5.2.8 on 2025-11-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric_craze_app', '0002_crouseldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
