# Generated by Django 5.2.8 on 2025-11-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric_craze_app', '0003_livestream_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_code', models.PositiveIntegerField()),
                ('version_name', models.CharField(max_length=20)),
                ('download_link', models.URLField()),
                ('force_update', models.BooleanField(default=False)),
                ('release_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
