# Generated by Django 5.2.8 on 2025-11-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric_craze_app', '0004_appversion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appversion',
            name='download_link',
        ),
        migrations.AddField(
            model_name='appversion',
            name='apk_file',
            field=models.FileField(blank=True, help_text='Upload APK here', null=True, upload_to='apks/'),
        ),
    ]
