# Generated by Django 5.2.8 on 2025-11-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cric_craze_app', '0005_remove_appversion_download_link_appversion_apk_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appversion',
            name='apk_file',
        ),
        migrations.AddField(
            model_name='appversion',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
